services:
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - 3306:3306
    expose:
      - 3306
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    expose:
      - 3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database:3306
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
    depends_on:
      - database
